-- Run this in Supabase Dashboard > SQL Editor.
-- The anon key is safe to use in the browser only when RLS policies are enabled.

create table if not exists public.rsvp (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  guest_id uuid unique,
  full_name text not null check (char_length(trim(full_name)) between 2 and 120),
  attendance text not null check (attendance in ('attending', 'declining')),
  plus_one_count integer not null default 0 check (plus_one_count between 0 and 5),
  dietary_notes text,
  wishes text,
  approved boolean not null default false
);

create table if not exists public.guests (
  id uuid primary key default gen_random_uuid(),
  full_name text not null unique,
  created_at timestamptz not null default now()
);

alter table public.rsvp add column if not exists guest_id uuid;
create unique index if not exists rsvp_guest_id_unique on public.rsvp(guest_id);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'rsvp_guest_id_fkey') then
    alter table public.rsvp add constraint rsvp_guest_id_fkey
      foreign key (guest_id) references public.guests(id) on delete restrict;
  end if;
end $$;

alter table public.rsvp enable row level security;
alter table public.guests enable row level security;

-- Guests may submit an RSVP. Reads are limited to approved wishes only.
drop policy if exists "Anyone can submit an RSVP" on public.rsvp;
create policy "Anyone can submit an RSVP"
on public.rsvp for insert
to anon, authenticated
with check (
  char_length(trim(full_name)) between 2 and 120
  and attendance in ('attending', 'declining')
  and plus_one_count between 0 and 5
);

drop policy if exists "Anyone can read approved wishes" on public.rsvp;
create policy "Anyone can read approved wishes"
on public.rsvp for select
to anon, authenticated
using (approved = true);

drop policy if exists "Anyone can read guest names" on public.guests;
drop policy if exists "Anyone can read guest list" on public.guests;
create policy "Anyone can read guest list"
on public.guests for select
to anon, authenticated
using (true);

drop policy if exists "Guests can update their RSVP" on public.rsvp;
create policy "Guests can update their RSVP"
on public.rsvp for update
to anon, authenticated
using (true)
with check (plus_one_count between 0 and 5 and attendance in ('attending', 'declining'));

-- Enable this if you want the Realtime guestbook subscription in index.html.
do $$
begin
  if not exists (
    select 1 
    from pg_publication_tables 
    where pubname = 'supabase_realtime' 
      and schemaname = 'public' 
      and tablename = 'rsvp'
  ) then
    alter publication supabase_realtime add table public.rsvp;
  end if;
end $$;

-- Review submissions in the Supabase table editor, then approve guestbook wishes:
-- update public.rsvp set approved = true where id = 1;

-- Add the expected invitees in the table editor, for example:
-- insert into public.guests (full_name) values ('Alex Guest'), ('Taylor Guest');
